sudo: required

services:
  - docker

language: ruby

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.1.15.0
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

cache: bundler

script: bundle exec rake test
