sudo: required

services:
  - docker

language: ruby

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.2.0.0
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

# Doesn't currently work with MRI 2.5.1: https://github.com/travis-ci/travis-ci/issues/8978
# cache: bundler

script: bundle exec rake test
